SELECT 
    B.MEMBER_NAME, 
    C.REVIEW_TEXT, 
    C.REVIEW_DATE
FROM MEMBER_PROFILE B
INNER JOIN REST_REVIEW C
    ON B.MEMBER_ID = C.MEMBER_ID
WHERE B.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
)
ORDER BY C.REVIEW_DATE ASC, C.REVIEW_TEXT ASC;