SELECT A.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO A
    INNER JOIN ITEM_TREE B
    ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IN (
        SELECT ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY = 'RARE'
)
ORDER BY A.ITEM_ID DESC