# 21년 가입 전체 회원
# 상품을 구매한 회원 수, 상품을 구매한 회원의 비율 년 월 별로 출력

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(USER_ID) 
                            FROM USER_INFO 
                            WHERE JOINED LIKE '2021%'), 1) AS PURCHASED_RATIO
FROM USER_INFO A
    INNER JOIN ONLINE_SALE B
    ON A.USER_ID = B.USER_ID
WHERE A.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
