SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * C.SOLD_BOOKS_CNT) AS TOTAL_SALES
FROM AUTHOR A
    INNER JOIN BOOK B
    ON A.AUTHOR_ID = B.AUTHOR_ID
    INNER JOIN (SELECT BOOK_ID, SUM(SALES) AS SOLD_BOOKS_CNT
        FROM BOOK_SALES
        WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
        GROUP BY BOOK_ID) C
    ON B.BOOK_ID = C.BOOK_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
