SELECT B.HISTORY_ID,
    FLOOR(A.DAILY_FEE * (1 - IFNULL(C.DISCOUNT_RATE , 0) / 100) *  (DATEDIFF(B.END_DATE, B.START_DATE) + 1)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE
    AND C.DURATION_TYPE = (CASE 
                            WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 90 THEN '90일 이상'
                            WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 30 THEN '30일 이상'
                            WHEN DATEDIFF(B.END_DATE, B.START_DATE) + 1 >= 7 THEN '7일 이상'
                           END)
WHERE A.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC