

SELECT C.FLAVOR
FROM (SELECT A.FLAVOR, SUM(SUMS + A.TOTAL_ORDER) AS REAL_SUMS
        FROM FIRST_HALF A
            INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUMS
                        FROM JULY
                        GROUP BY FLAVOR) B
                ON A.FLAVOR = B.FLAVOR
        GROUP BY A.FLAVOR
        ORDER BY REAL_SUMS DESC) C
LIMIT 3
